# Generated by Django 4.2.6 on 2023-11-04 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_bid_time_alter_comment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 15, 14, 35, 344820)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 15, 14, 35, 344504)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
